import type { DetectionRule } from './types.js';

/**
 * Cloud infrastructure security rules
 * AWS, Azure, GCP, Terraform, CloudFormation
 */

export const cloudRules: DetectionRule[] = [
  {
    id: 'VG-CLOUD-001',
    title: 'S3 Bucket Public Read',
    category: 'cloud',
    severity: 'critical',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /ACL\s*[:=]\s*['"]public-read['"]/gi,
    confidence: 'high',
    message: 'S3 bucket configured with public read access',
    remediation: 'Remove public ACL, use bucket policies with conditions',
    cwe: 'CWE-732',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-002',
    title: 'IAM Wildcard Permissions',
    category: 'cloud',
    severity: 'critical',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /"Action"\s*:\s*"\*"/g,
    confidence: 'high',
    message: 'IAM policy grants wildcard permissions',
    remediation: 'Follow principle of least privilege, specify exact actions',
    cwe: 'CWE-269',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-003',
    title: 'Security Group Open to World',
    category: 'cloud',
    severity: 'critical',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /(?:cidr_blocks|CidrIp)\s*[:=]\s*\[?\s*["']0\.0\.0\.0\/0["']/gi,
    confidence: 'high',
    message: 'Security group allows access from 0.0.0.0/0',
    remediation: 'Restrict to specific IP ranges or use VPN',
    cwe: 'CWE-668',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-004',
    title: 'Unencrypted Storage',
    category: 'cloud',
    severity: 'warning',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /(?:encrypted|encryption)\s*[:=]\s*(?:false|False|no)/gi,
    confidence: 'medium',
    message: 'Cloud storage configured without encryption',
    remediation: 'Enable encryption at rest with KMS keys',
    cwe: 'CWE-311',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-005',
    title: 'RDS Without Encryption',
    category: 'cloud',
    severity: 'warning',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /aws_db_instance.*(?!.*storage_encrypted\s*=\s*true)/gs,
    confidence: 'medium',
    message: 'RDS instance created without storage encryption',
    remediation: 'Enable storage_encrypted = true',
    cwe: 'CWE-311',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-006',
    title: 'Missing KMS Encryption',
    category: 'cloud',
    severity: 'warning',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /(?:aws_ebs_volume|aws_s3_bucket).*(?!.*kms_key_id)/gs,
    confidence: 'low',
    message: 'Resource missing KMS encryption key',
    remediation: 'Specify kms_key_id for customer-managed keys',
    cwe: 'CWE-311',
    fixable: false,
  },
  {
    id: 'VG-CLOUD-007',
    title: 'Azure Storage Public Access',
    category: 'cloud',
    severity: 'critical',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['**/*.tf', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /allow_blob_public_access\s*=\s*true/gi,
    confidence: 'high',
    message: 'Azure storage allows public blob access',
    remediation: 'Set allow_blob_public_access = false',
    cwe: 'CWE-732',
    fixable: false,
  },
];
