import type { DetectionRule } from './types.js';

/**
 * Cryptography security rules
 * Detects weak algorithms, hardcoded keys, insecure practices
 */

export const cryptoRules: DetectionRule[] = [
  {
    id: 'VG-CRYPTO-001',
    title: 'Weak Hash Algorithm (MD5)',
    category: 'crypto',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /\b(md5|MD5)\s*\(/g,
    confidence: 'high',
    message: 'MD5 is cryptographically broken, use SHA-256 or better',
    remediation: 'Replace with SHA-256, SHA-3, or bcrypt for passwords',
    cwe: 'CWE-327',
    fixable: false,
  },
  {
    id: 'VG-CRYPTO-002',
    title: 'Weak Hash Algorithm (SHA1)',
    category: 'crypto',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /\b(sha1|SHA1)\s*\(/g,
    confidence: 'high',
    message: 'SHA-1 is deprecated, use SHA-256 or better',
    remediation: 'Replace with SHA-256, SHA-3, or bcrypt for passwords',
    cwe: 'CWE-327',
    fixable: false,
  },
  {
    id: 'VG-CRYPTO-003',
    title: 'Insecure Random for Crypto',
    category: 'crypto',
    severity: 'critical',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts'],
    pattern: /Math\.random\(\).*(?:key|token|secret|salt|iv|nonce)/gi,
    confidence: 'high',
    message: 'Math.random() is not cryptographically secure',
    remediation: 'Use crypto.randomBytes() or crypto.getRandomValues()',
    cwe: 'CWE-338',
    fixable: false,
  },
  {
    id: 'VG-CRYPTO-004',
    title: 'Hardcoded Encryption Key',
    category: 'crypto',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(encryption[_-]?key|encrypt[_-]?key)\s*[:=]\s*['"][^'"]{16,}['"]/gi,
    confidence: 'high',
    message: 'Encryption key hardcoded in source',
    remediation: 'Load encryption keys from secure key management systems',
    cwe: 'CWE-321',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-CRYPTO-005',
    title: 'Hardcoded Salt/IV',
    category: 'crypto',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(salt|iv|initialization[_-]?vector)\s*[:=]\s*['"][^'"]{8,}['"]/gi,
    confidence: 'medium',
    message: 'Cryptographic salt or IV hardcoded',
    remediation: 'Generate random salts/IVs for each encryption operation',
    cwe: 'CWE-329',
    fixable: false,
  },
  {
    id: 'VG-CRYPTO-006',
    title: 'ECB Mode Usage',
    category: 'crypto',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /['"](AES-ECB|DES-ECB)['"]/g,
    confidence: 'high',
    message: 'ECB mode is insecure, use CBC, GCM, or CTR',
    remediation: 'Replace with AES-GCM or AES-CBC with random IV',
    cwe: 'CWE-327',
    fixable: false,
  },
  {
    id: 'VG-CRYPTO-007',
    title: 'Weak Key Size',
    category: 'crypto',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(?:keySize|key[_-]?size|modulusLength)\s*[:=]\s*(512|1024)\b/gi,
    confidence: 'high',
    message: 'Weak cryptographic key size detected',
    remediation: 'Use at least 2048-bit keys for RSA, 256-bit for symmetric',
    cwe: 'CWE-326',
    fixable: false,
  },
];
