import type { DetectionRule } from './types.js';

export const dockerRules: DetectionRule[] = [
  {
    id: 'VG-DOCK-001',
    title: 'Container Running as Root',
    severity: 'warning',
    category: 'docker',
    languages: ['docker'],
    filePatterns: ['Dockerfile', '*.dockerfile', 'Dockerfile.*'],
    pattern: /^(?!.*\bUSER\b).*$/gm,
    message: 'Dockerfile has no USER directive. Container runs as root by default.',
    remediation: 'Add USER directive to run as non-root. Example: USER 1000:1000',
    confidence: 'medium',
    cwe: 'CWE-250',
    owasp: 'A05:2021',
  },
  {
    id: 'VG-DOCK-002',
    title: 'Docker Socket Exposed',
    severity: 'critical',
    category: 'docker',
    languages: ['docker', 'yaml'],
    filePatterns: ['docker-compose.yml', 'docker-compose.yaml', '*.yml', '*.yaml'],
    pattern: /\/var\/run\/docker\.sock/g,
    message: 'Docker socket mounted into container. Grants full host control.',
    remediation: 'Remove docker.sock mount. Use Docker API over TCP with TLS if needed.',
    confidence: 'high',
    cwe: 'CWE-269',
    owasp: 'A05:2021',
  },
  {
    id: 'VG-DOCK-003',
    title: 'Privileged Container',
    severity: 'critical',
    category: 'docker',
    languages: ['docker', 'yaml', 'kubernetes'],
    filePatterns: ['docker-compose.yml', 'docker-compose.yaml', '*.yml', '*.yaml'],
    pattern: /(?:--privileged|privileged\s*:\s*true)/g,
    message: 'Privileged container has full host access. Attacker can escape container.',
    remediation: 'Remove privileged flag. Use specific capabilities if needed.',
    confidence: 'high',
    cwe: 'CWE-250',
    owasp: 'A05:2021',
  },
];
