import type { DetectionRule } from './types.js';

/**
 * General security best practices
 * Hardcoded IPs, debug mode, permissions, etc.
 */

export const generalRules: DetectionRule[] = [
  {
    id: 'VG-GEN-001',
    title: 'Hardcoded IP Address',
    category: 'config',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.yaml', '**/*.yml'],
    pattern: /['"](?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)['"]/g,
    confidence: 'medium',
    message: 'Hardcoded IP address detected',
    remediation: 'Use environment variables or service discovery',
    cwe: 'CWE-547',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-GEN-002',
    title: 'Debug Mode in Production',
    category: 'config',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.env*', '**/*.yaml'],
    pattern: /(?:DEBUG|debug|FLASK_DEBUG|NODE_ENV)\s*[:=]\s*['"]?(?:true|True|1|development)['"']?/gi,
    confidence: 'medium',
    message: 'Debug mode may be enabled in production',
    remediation: 'Ensure DEBUG=false in production environments',
    cwe: 'CWE-489',
    fixable: false,
  },
  {
    id: 'VG-GEN-003',
    title: 'Excessive File Permissions',
    category: 'config',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.sh'],
    pattern: /chmod\s+(?:777|666)/g,
    confidence: 'high',
    message: 'Overly permissive file permissions (777/666)',
    remediation: 'Use restrictive permissions (644 for files, 755 for dirs)',
    cwe: 'CWE-732',
    fixable: false,
  },
  {
    id: 'VG-GEN-004',
    title: 'Commented Credentials',
    category: 'secrets',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /\/\/.*(?:password|passwd|pwd|secret|key|token)\s*[:=]/gi,
    confidence: 'low',
    message: 'Potential credentials in comments',
    remediation: 'Remove commented credentials, rotate if exposed',
    cwe: 'CWE-615',
    fixable: false,
  },
  {
    id: 'VG-GEN-005',
    title: 'Hardcoded Database Host',
    category: 'config',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.yaml', '**/*.yml'],
    pattern: /(?:host|hostname|db[_-]?host)\s*[:=]\s*['"](?:localhost|127\.0\.0\.1|[a-z0-9-]+\.(?:rds\.amazonaws\.com|database\.windows\.net|sql\.goog))['"]/gi,
    confidence: 'medium',
    message: 'Database hostname hardcoded',
    remediation: 'Use environment variables for database hosts',
    cwe: 'CWE-547',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-GEN-006',
    title: 'TODO Security Note',
    category: 'general',
    severity: 'info',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(?:TODO|FIXME|XXX).*(?:security|auth|permission|encrypt|sanitize)/gi,
    confidence: 'low',
    message: 'Security-related TODO comment found',
    remediation: 'Address security TODOs before production',
    cwe: 'CWE-1188',
    fixable: false,
  },
];
