import type { DetectionRule } from './types.js';

export const kubernetesRules: DetectionRule[] = [
  {
    id: 'VG-K8S-001',
    title: 'Cluster-Admin Role Binding',
    severity: 'critical',
    category: 'kubernetes',
    languages: ['kubernetes', 'yaml'],
    filePatterns: ['*.yml', '*.yaml'],
    pattern: /cluster-?admin/gi,
    message: 'cluster-admin role grants full cluster access. Compromised pod = compromised cluster.',
    remediation: 'Use least-privilege RBAC. Create specific roles for required permissions.',
    confidence: 'high',
    cwe: 'CWE-250',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-K8S-002',
    title: 'Open Ingress Rules (0.0.0.0/0)',
    severity: 'critical',
    category: 'kubernetes',
    languages: ['kubernetes', 'yaml'],
    filePatterns: ['*.yml', '*.yaml'],
    pattern: /(?:0\.0\.0\.0\/0|::\/0)/g,
    message: 'Network policy allows traffic from any IP. Service exposed to entire internet.',
    remediation: 'Restrict ingress to specific CIDR blocks or pod selectors.',
    confidence: 'high',
    cwe: 'CWE-284',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-K8S-003',
    title: 'Missing runAsNonRoot',
    severity: 'warning',
    category: 'kubernetes',
    languages: ['kubernetes', 'yaml'],
    filePatterns: ['*.yml', '*.yaml'],
    pattern: /securityContext:(?:(?!runAsNonRoot\s*:\s*true)[\s\S])*?(?=securityContext:|$)/g,
    message: 'Pod security context missing runAsNonRoot:true. Container may run as root.',
    remediation: 'Add securityContext.runAsNonRoot: true to pod spec.',
    confidence: 'medium',
    cwe: 'CWE-250',
    owasp: 'A05:2021',
  },
];
