import type { DetectionRule } from './types.js';

export const nodeRules: DetectionRule[] = [
  {
    id: 'VG-NODE-001',
    title: 'Child Process Exec',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:child_process\.)?exec(?:Sync)?\s*\(`/g,
    message: 'child_process.exec() runs commands in a shell. Untrusted input leads to command injection.',
    remediation: 'Use child_process.spawn() or execFile() with argument arrays. Never pass user input to shell.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-002',
    title: 'Spawn with Shell',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /spawn\s*\([^)]*\{\s*[^}]*shell\s*:\s*true/g,
    message: 'spawn() with shell:true enables command injection via untrusted arguments.',
    remediation: 'Remove shell:true. Pass commands and args separately.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-003',
    title: 'Unsafe HTML Rendering (React)',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.jsx', '*.tsx', '*.js', '*.ts'],
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\s*\{?\s*__html\s*:/g,
    message: 'dangerouslySetInnerHTML renders raw HTML. User input causes XSS.',
    remediation: 'Sanitize HTML with DOMPurify before rendering, or avoid raw HTML entirely.',
    confidence: 'high',
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-004',
    title: 'Disabled TLS Verification',
    severity: 'critical',
    category: 'crypto',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /rejectUnauthorized\s*:\s*false/g,
    message: 'TLS certificate verification disabled. Vulnerable to MITM attacks.',
    remediation: 'Remove rejectUnauthorized:false. Fix certificate chain issues properly.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
  },
  {
    id: 'VG-NODE-005',
    title: 'TLS Reject Env Bypass',
    severity: 'critical',
    category: 'crypto',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0/g,
    message: 'NODE_TLS_REJECT_UNAUTHORIZED=0 disables all TLS verification globally.',
    remediation: 'Never disable TLS verification. Fix certificate issues at the source.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
  },
];
