import type { DetectionRule } from './types.js';

export const nodeRules: DetectionRule[] = [
  {
    id: 'VG-NODE-001',
    title: 'Child Process Exec',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    // Match exec()/execSync() where the argument is built dynamically:
    // - template literal:  exec(`ls ${dir}`)
    // - string concat:     exec("ls " + dir)
    // - bare identifier:   exec(cmd)
    pattern: /(?:child_process\.)?exec(?:Sync)?\s*\(\s*(?:`[^`]*\$\{|[`'"][^`'"]*[`'"]\s*\+|\w+\s*\))/g,
    message: 'child_process.exec() runs commands in a shell. Dynamic input leads to command injection.',
    remediation: 'Use child_process.spawn() or execFile() with argument arrays. Never pass user input to shell.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-002',
    title: 'Spawn with Shell',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /spawn\s*\([^)]*\{\s*[^}]*shell\s*:\s*true/g,
    message: 'spawn() with shell:true enables command injection via untrusted arguments.',
    remediation: 'Remove shell:true. Pass commands and args separately.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-003',
    title: 'Unsafe HTML Rendering (React)',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.jsx', '*.tsx', '*.js', '*.ts'],
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\s*\{?\s*__html\s*:/g,
    message: 'dangerouslySetInnerHTML renders raw HTML. User input causes XSS.',
    remediation: 'Sanitize HTML with DOMPurify before rendering, or avoid raw HTML entirely.',
    confidence: 'high',
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-004',
    title: 'Disabled TLS Verification',
    severity: 'critical',
    category: 'crypto',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /rejectUnauthorized\s*:\s*false/g,
    message: 'TLS certificate verification disabled. Vulnerable to MITM attacks.',
    remediation: 'Remove rejectUnauthorized:false. Fix certificate chain issues properly.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
  },
  {
    id: 'VG-NODE-005',
    title: 'TLS Reject Env Bypass',
    severity: 'critical',
    category: 'crypto',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0/g,
    message: 'NODE_TLS_REJECT_UNAUTHORIZED=0 disables all TLS verification globally.',
    remediation: 'Never disable TLS verification. Fix certificate issues at the source.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
  },
  {
    id: 'VG-NODE-006',
    title: 'Request Data Used as File Path',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:readFile|readFileSync|createReadStream|sendFile)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as a file path, enabling path traversal and arbitrary file reads.',
    remediation: 'Resolve the path against a fixed base directory and reject paths that escape it.',
    confidence: 'high',
    cwe: 'CWE-22',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-NODE-007',
    title: 'Request Data Used as Outbound URL',
    severity: 'critical',
    category: 'web',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:fetch|got|https?\.(?:get|request)|undici\.request|axios\.(?:get|post|put|patch|delete|head|request))\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as an outbound URL, enabling server-side request forgery.',
    remediation: 'Allowlist destinations and reject private, loopback, link-local, and metadata-service addresses after DNS resolution.',
    confidence: 'high',
    cwe: 'CWE-918',
    owasp: 'A10:2021',
  },
  {
    id: 'VG-NODE-008',
    title: 'Request Data Used as MongoDB Query',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /\.(?:find|findOne|deleteOne|deleteMany|updateOne|updateMany|findOneAndUpdate)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])?/g,
    message: 'Request data is used directly as a MongoDB query, enabling operator injection and authorization bypass.',
    remediation: 'Build queries from allowlisted scalar fields and reject keys beginning with $ or containing dots.',
    confidence: 'high',
    cwe: 'CWE-943',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-009',
    title: 'Request Data Used as Module Path',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:require|import)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data controls a module path, enabling unintended code loading and path traversal.',
    remediation: 'Map allowlisted identifiers to fixed module paths; never accept a module path from a request.',
    confidence: 'high',
    cwe: 'CWE-94',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-010',
    title: 'Request Data Used as File Mutation Path',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:writeFile|writeFileSync|createWriteStream|unlink|unlinkSync|rm|rmSync|rename|renameSync)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as a file mutation path, enabling arbitrary file overwrite or deletion.',
    remediation: 'Resolve against a fixed base directory, reject escaping paths, and generate server-side filenames.',
    confidence: 'high',
    cwe: 'CWE-73',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-NODE-011',
    title: 'Request Data Used as Response Header',
    severity: 'critical',
    category: 'web',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:setHeader|res\.(?:header|set|append))\s*\(\s*[^,]+,\s*(?:req|request)\.(?:query|params|body|headers)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is copied directly into a response header, enabling HTTP response splitting.',
    remediation: 'Use fixed or allowlisted header values and reject carriage returns and line feeds.',
    confidence: 'high',
    cwe: 'CWE-113',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-012',
    title: 'Filesystem Root Exposed as Static Content',
    severity: 'critical',
    category: 'config',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /express\.static\s*\(\s*['"]\/(?:['"]|\*['"])/g,
    message: 'The filesystem root is exposed as static content, allowing disclosure of sensitive host files.',
    remediation: 'Serve only a dedicated public-assets directory with no secrets or application source.',
    confidence: 'high',
    cwe: 'CWE-552',
    owasp: 'A05:2021',
  },
  {
    id: 'VG-NODE-013',
    title: 'Request Data Used as Redirect Target',
    severity: 'critical',
    category: 'web',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:res\.)?redirect\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as a redirect target, enabling phishing through an open redirect.',
    remediation: 'Allow only relative paths or validate the destination host against a strict allowlist.',
    confidence: 'high',
    cwe: 'CWE-601',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-NODE-014',
    title: 'Request Data Used as SQL Statement',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /\.(?:query|execute)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is executed directly as a SQL statement, enabling SQL injection.',
    remediation: 'Use a fixed SQL statement with parameter placeholders and pass request values separately.',
    confidence: 'high',
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-015',
    title: 'Request Data Compiled as Template',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:ejs|pug|Handlebars|nunjucks)\.(?:compile|renderString)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is compiled as a server-side template, enabling template injection and code execution.',
    remediation: 'Compile only fixed, trusted templates and pass request data as escaped template context.',
    confidence: 'high',
    cwe: 'CWE-1336',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-NODE-016',
    title: 'Request Data Used as Regular Expression',
    severity: 'critical',
    category: 'web',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /new\s+RegExp\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data is compiled directly as a regular expression, enabling regular expression denial of service.',
    remediation: 'Use fixed expressions or escape input, constrain its length, and enforce execution time limits.',
    confidence: 'high',
    cwe: 'CWE-1333',
    owasp: 'A06:2021',
  },
  {
    id: 'VG-NODE-017',
    title: 'Request Data Used as Process Executable',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript'],
    filePatterns: ['*.js', '*.ts', '*.mjs', '*.cjs'],
    pattern: /(?:child_process\.)?(?:spawn|spawnSync|execFile|execFileSync)\s*\(\s*(?:req|request)\.(?:query|params|body)(?:\.[A-Za-z_$][\w$]*|\s*\[[^\]]+\])/g,
    message: 'Request data selects the executable for a child process, enabling arbitrary command execution.',
    remediation: 'Map allowlisted operation names to fixed executable paths and pass validated arguments separately.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
];
