import type { DetectionRule } from './types.js';

export const pythonRules: DetectionRule[] = [
  {
    id: 'VG-PY-001',
    title: 'Shell Command Exec (shell=True)',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /subprocess\.\w+\s*\([^)]*shell\s*=\s*True/g,
    message: 'subprocess with shell=True allows command injection if input is untrusted.',
    remediation: 'Use shell=False and pass arguments as a list. Validate/sanitize all inputs.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-002',
    title: 'OS System Call',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /os\.system\s*\(/g,
    message: 'os.system() executes shell commands. Vulnerable to command injection.',
    remediation: 'Use subprocess.run() with shell=False and argument list.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-003',
    title: 'Unsafe YAML Load',
    severity: 'critical',
    category: 'deserialization',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /yaml\.load\s*\([^)]*(?!Loader\s*=\s*yaml\.SafeLoader)/g,
    allowPatterns: [/yaml\.safe_load/],
    message: 'yaml.load() without SafeLoader can execute arbitrary Python objects.',
    remediation: 'Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader).',
    confidence: 'high',
    cwe: 'CWE-502',
    owasp: 'A08:2021',
  },
  {
    id: 'VG-PY-004',
    title: 'Insecure Pickle Deserialization',
    severity: 'critical',
    category: 'deserialization',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /pickle\.loads?\s*\(/g,
    message: 'pickle deserializes arbitrary Python objects. Malicious payloads achieve RCE.',
    remediation: 'Use JSON or other safe serialization. Never unpickle untrusted data.',
    confidence: 'high',
    cwe: 'CWE-502',
    owasp: 'A08:2021',
  },
  {
    id: 'VG-PY-005',
    title: 'Flask Debug Mode Enabled',
    severity: 'critical',
    category: 'config',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /app\.run\s*\([^)]*debug\s*=\s*True/g,
    message: 'Flask debug mode exposes interactive debugger. Attackers can execute code via Werkzeug console.',
    remediation: 'Set debug=False in production. Use environment variables for config.',
    confidence: 'high',
    cwe: 'CWE-489',
    owasp: 'A05:2021',
  },
  {
    id: 'VG-PY-006',
    title: 'Disabled SSL Verification',
    severity: 'critical',
    category: 'crypto',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /requests\.(?:get|post|put|delete|patch|head|options)\s*\([^)]*verify\s*=\s*False/g,
    message: 'SSL verification disabled. Vulnerable to man-in-the-middle attacks.',
    remediation: 'Remove verify=False. Fix certificate issues properly.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
  },
];
