import type { DetectionRule } from './types.js';

export const pythonRules: DetectionRule[] = [
  {
    id: 'VG-PY-001',
    title: 'Shell Command Exec (shell=True)',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /subprocess\.\w+\s*\([^)]*shell\s*=\s*True/g,
    message: 'subprocess with shell=True allows command injection if input is untrusted.',
    remediation: 'Use shell=False and pass arguments as a list. Validate/sanitize all inputs.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
    fixable: true,
    fixStrategy: 'shell-true-to-false',
  },
  {
    id: 'VG-PY-002',
    title: 'OS System Call',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /os\.system\s*\(/g,
    message: 'os.system() executes shell commands. Vulnerable to command injection.',
    remediation: 'Use subprocess.run() with shell=False and argument list.',
    confidence: 'high',
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-003',
    title: 'Unsafe YAML Load',
    severity: 'critical',
    category: 'deserialization',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /yaml\.load\s*\([^)]*(?!Loader\s*=\s*yaml\.SafeLoader)/g,
    allowPatterns: [/yaml\.safe_load/],
    message: 'yaml.load() without SafeLoader can execute arbitrary Python objects.',
    remediation: 'Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader).',
    confidence: 'high',
    cwe: 'CWE-502',
    owasp: 'A08:2021',
  },
  {
    id: 'VG-PY-004',
    title: 'Insecure Pickle Deserialization',
    severity: 'critical',
    category: 'deserialization',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /pickle\.loads?\s*\(/g,
    message: 'pickle deserializes arbitrary Python objects. Malicious payloads achieve RCE.',
    remediation: 'Use JSON or other safe serialization. Never unpickle untrusted data.',
    confidence: 'high',
    cwe: 'CWE-502',
    owasp: 'A08:2021',
  },
  {
    id: 'VG-PY-005',
    title: 'Flask Debug Mode Enabled',
    severity: 'critical',
    category: 'config',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /app\.run\s*\([^)]*debug\s*=\s*True/g,
    message: 'Flask debug mode exposes interactive debugger. Attackers can execute code via Werkzeug console.',
    remediation: 'Set debug=False in production. Use environment variables for config.',
    confidence: 'high',
    cwe: 'CWE-489',
    owasp: 'A05:2021',
  },
  {
    id: 'VG-PY-006',
    title: 'Disabled SSL Verification',
    severity: 'critical',
    category: 'crypto',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /requests\.(?:get|post|put|delete|patch|head|options)\s*\([^)]*verify\s*=\s*False/g,
    message: 'SSL verification disabled. Vulnerable to man-in-the-middle attacks.',
    remediation: 'Remove verify=False. Fix certificate issues properly.',
    confidence: 'high',
    cwe: 'CWE-295',
    owasp: 'A02:2021',
    fixable: true,
    fixStrategy: 'remove-verify-false',
  },
  {
    id: 'VG-PY-007',
    title: 'Request Data Used as File Path',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /(?:open|send_file|Path)\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as a file path, enabling path traversal and arbitrary file reads.',
    remediation: 'Resolve the path against a fixed base directory and reject paths that escape it.',
    confidence: 'high',
    cwe: 'CWE-22',
    owasp: 'A01:2021',
  },
  {
    id: 'VG-PY-008',
    title: 'Request Data Used as Outbound URL',
    severity: 'critical',
    category: 'web',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /(?:(?:requests|httpx)\.(?:get|post|put|patch|delete|head|request)|urllib\.request\.urlopen)\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as an outbound URL, enabling server-side request forgery.',
    remediation: 'Allowlist destinations and reject private, loopback, link-local, and metadata-service addresses after DNS resolution.',
    confidence: 'high',
    cwe: 'CWE-918',
    owasp: 'A10:2021',
  },
  {
    id: 'VG-PY-009',
    title: 'Request Data Used as SQL Statement',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /\.execute(?:many)?\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is executed directly as a SQL statement, enabling SQL injection.',
    remediation: 'Use a fixed SQL statement with parameter placeholders and pass request values separately.',
    confidence: 'high',
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-010',
    title: 'Request Data Used as Jinja Template',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /(?:render_template_string|Environment\([^)]*\)\.from_string|jinja2\.Template)\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is compiled as a Jinja template, enabling server-side template injection and code execution.',
    remediation: 'Render a fixed template and pass request data only as template context variables.',
    confidence: 'high',
    cwe: 'CWE-1336',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-011',
    title: 'Request Data Used as Python Code',
    severity: 'critical',
    category: 'injection',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /(?:eval|exec|compile)\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is evaluated as Python code, enabling remote code execution.',
    remediation: 'Replace dynamic evaluation with explicit parsing and an allowlist of supported operations.',
    confidence: 'high',
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'VG-PY-012',
    title: 'Request Data Used as Redirect Target',
    severity: 'critical',
    category: 'web',
    languages: ['python'],
    filePatterns: ['*.py'],
    pattern: /(?:redirect|HttpResponseRedirect|HttpResponsePermanentRedirect)\s*\(\s*request\.(?:args|form|values|GET|POST)(?:\.get\s*\([^)]*\)|\s*\[[^\]]+\])/g,
    message: 'Request data is used directly as a redirect target, enabling phishing through an open redirect.',
    remediation: 'Allow only relative paths or validate the destination host against a strict allowlist.',
    confidence: 'high',
    cwe: 'CWE-601',
    owasp: 'A01:2021',
  },
];
