import type { DetectionRule } from './types.js';

/**
 * Extended secret detection rules
 * Covers cloud providers, payment APIs, and more
 */

export const secretsExtendedRules: DetectionRule[] = [
  {
    id: 'VG-SEC-006',
    title: 'AWS Access Key',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.yaml', '**/*.yml', '**/*.json'],
    pattern: /AKIA[0-9A-Z]{16}/g,
    confidence: 'high',
    message: 'AWS Access Key ID detected in code',
    remediation: 'Use AWS IAM roles or environment variables',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-007',
    title: 'AWS Secret Key',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.yaml', '**/*.yml', '**/*.json', '**/*.env*'],
    pattern: /aws_secret_access_key\s*=\s*['"][^'"]{40}['"]/gi,
    confidence: 'high',
    message: 'AWS Secret Access Key detected',
    remediation: 'Use AWS Secrets Manager or environment variables',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-008',
    title: 'GCP Service Account Key',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.json'],
    pattern: /"type"\s*:\s*"service_account"/g,
    confidence: 'high',
    message: 'GCP service account JSON key detected',
    remediation: 'Use Google Cloud Secret Manager or Workload Identity',
    cwe: 'CWE-798',
    fixable: false,
  },
  {
    id: 'VG-SEC-009',
    title: 'Azure Connection String',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py', '**/*.json', '**/*.yaml'],
    pattern: /AccountKey=[A-Za-z0-9+/]{88}==/g,
    confidence: 'high',
    message: 'Azure Storage Account Key detected',
    remediation: 'Use Azure Key Vault or Managed Identities',
    cwe: 'CWE-798',
    fixable: false,
  },
  {
    id: 'VG-SEC-010',
    title: 'Private Key in Code',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*'],
    pattern: /-----BEGIN\s+(RSA|EC|OPENSSH)\s+PRIVATE\s+KEY-----/g,
    confidence: 'high',
    message: 'Private cryptographic key detected in code',
    remediation: 'Store private keys in secure key management systems',
    cwe: 'CWE-798',
    fixable: false,
  },
  {
    id: 'VG-SEC-011',
    title: 'Stripe API Key',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(sk|pk)_(test|live)_[0-9a-zA-Z]{24,}/g,
    confidence: 'high',
    message: 'Stripe API key detected',
    remediation: 'Use environment variables for API keys',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-012',
    title: 'GitHub Token',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /gh[puo]_[A-Za-z0-9_]{36,}/g,
    confidence: 'high',
    message: 'GitHub personal access token detected',
    remediation: 'Use GitHub Secrets or environment variables',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-013',
    title: 'Slack Webhook URL',
    category: 'secrets',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /https:\/\/hooks\.slack\.com\/services\/[A-Z0-9]{9,}\/[A-Z0-9]{9,}\/[a-zA-Z0-9]{24}/g,
    confidence: 'high',
    message: 'Slack webhook URL detected',
    remediation: 'Store webhook URLs in environment variables',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-014',
    title: 'JWT Secret',
    category: 'secrets',
    severity: 'critical',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /jwt[_-]?secret\s*[:=]\s*['"][^'"]{8,}['"]/gi,
    confidence: 'medium',
    message: 'JWT secret hardcoded in application',
    remediation: 'Use environment variables for JWT secrets',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
  {
    id: 'VG-SEC-015',
    title: 'Generic API Key Pattern',
    category: 'secrets',
    severity: 'warning',
    languages: ['node', 'python', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.py'],
    pattern: /(api[_-]?key|apikey)\s*[:=]\s*['"][a-zA-Z0-9]{20,}['"]/gi,
    confidence: 'medium',
    message: 'Potential API key detected',
    remediation: 'Use environment variables or secret managers',
    cwe: 'CWE-798',
    fixable: true,
    fixStrategy: 'hardcoded-to-env',
  },
];
