import type { DetectionRule } from './types.js';

export const secretsRules: DetectionRule[] = [
  {
    id: 'VG-SEC-001',
    title: 'Dynamic Code Execution (eval)',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['*.js', '*.ts', '*.jsx', '*.tsx', '*.mjs', '*.cjs', '*.py'],
    pattern: /\beval\s*\(/g,
    message: 'eval() executes arbitrary code. Attacker-controlled input leads to RCE.',
    remediation: 'Use JSON.parse() for data, or a sandboxed interpreter if dynamic execution is required.',
    confidence: 'high',
    cwe: 'CWE-95',
    owasp: 'A03:2021',
    aiVerification: { enabled: true },
  },
  {
    id: 'VG-SEC-002',
    title: 'SQL String Concatenation',
    severity: 'critical',
    category: 'injection',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['*.js', '*.ts', '*.jsx', '*.tsx', '*.mjs', '*.cjs', '*.py'],
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)[\s\S]{0,50}(?:\+\s*\w+|\$\{|f['"])/gi,
    message: 'SQL query built with string concatenation. Vulnerable to SQL injection.',
    remediation: 'Use parameterized queries or prepared statements.',
    confidence: 'medium',
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    aiVerification: { enabled: true },
  },
  {
    id: 'VG-SEC-003',
    title: 'Hardcoded Secret/Credential',
    severity: 'critical',
    category: 'secrets',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['*.js', '*.ts', '*.jsx', '*.tsx', '*.mjs', '*.cjs', '*.py', '*.json', '*.yaml', '*.yml'],
    pattern: /(?:api[_-]?key|secret|password|token|auth[_-]?token|private[_-]?key)\s*[:=]\s*['"][A-Za-z0-9+/=_-]{16,}['"]/gi,
    allowPatterns: [/example|placeholder|your[_-]?|changeme|xxx|test|dummy/i],
    message: 'Hardcoded credential detected. Secrets in source code can be extracted from version control.',
    remediation: 'Use environment variables or a secrets manager (AWS Secrets Manager, HashiCorp Vault).',
    confidence: 'high',
    cwe: 'CWE-798',
    owasp: 'A07:2021',
    aiVerification: { enabled: true },
  },
  {
    id: 'VG-SEC-004',
    title: 'Secret Logged to Console',
    severity: 'warning',
    category: 'secrets',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['*.js', '*.ts', '*.jsx', '*.tsx', '*.mjs', '*.cjs', '*.py'],
    pattern: /(?:console\.log|print)\s*\([^)]*(?:key|token|password|secret|credential|api[_-]?key)/gi,
    message: 'Potentially logging sensitive data. Logs may be accessible to unauthorized parties.',
    remediation: 'Remove secret logging or redact sensitive values before logging.',
    confidence: 'medium',
    cwe: 'CWE-532',
    owasp: 'A09:2021',
    aiVerification: { enabled: true },
  },
  {
    id: 'VG-SEC-005',
    title: 'Secret in API Response',
    severity: 'warning',
    category: 'secrets',
    languages: ['node', 'typescript', 'python'],
    filePatterns: ['*.js', '*.ts', '*.jsx', '*.tsx', '*.mjs', '*.cjs', '*.py'],
    pattern: /(?:res\.json|jsonify|return\s*\{)[^}]*(?:api_key|password|secret|token|private_key)\s*:/gi,
    message: 'API response may include sensitive fields. Secrets exposed to clients.',
    remediation: 'Filter sensitive fields before sending response. Use DTOs or serializers.',
    confidence: 'medium',
    cwe: 'CWE-200',
    owasp: 'A01:2021',
    aiVerification: { enabled: true },
  },
];
