import type { DetectionRule } from './types.js';

/**
 * Web security rules
 * CORS, cookies, XSS, redirects, headers
 */

export const webRules: DetectionRule[] = [
  {
    id: 'VG-WEB-001',
    title: 'CORS Wildcard Origin',
    category: 'web',
    severity: 'critical',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.mjs', '**/*.cjs'],
    // Matches:
    //   Access-Control-Allow-Origin: '*'  (raw header)
    //   cors({ origin: '*' })             (express cors middleware)
    //   res.header('Access-Control-Allow-Origin', '*')
    pattern: /(?:Access-Control-Allow-Origin['"]?\s*[:,]\s*['"][*]['"]|origin\s*:\s*['"][*]['"])/gi,
    confidence: 'high',
    message: 'CORS allows all origins (*), exposing sensitive data',
    remediation: 'Whitelist specific origins or use credentials: false',
    cwe: 'CWE-942',
    fixable: false,
  },
  {
    id: 'VG-WEB-002',
    title: 'Insecure Cookie',
    category: 'web',
    severity: 'warning',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts'],
    pattern: /(?:setHeader|setCookie).*(?!.*secure)(?!.*httponly)/gi,
    confidence: 'medium',
    message: 'Cookie missing Secure and HttpOnly flags',
    remediation: 'Set Secure and HttpOnly flags on sensitive cookies',
    cwe: 'CWE-614',
    fixable: false,
  },
  {
    id: 'VG-WEB-003',
    title: 'Open Redirect',
    category: 'web',
    severity: 'warning',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts'],
    pattern: /(?:redirect|location)\s*=\s*(?:req\.query|req\.params|request\.GET)/gi,
    confidence: 'medium',
    message: 'Potential open redirect vulnerability',
    remediation: 'Validate redirect URLs against whitelist',
    cwe: 'CWE-601',
    fixable: false,
  },
  {
    id: 'VG-WEB-004',
    title: 'XSS in Template',
    category: 'web',
    severity: 'critical',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.jsx', '**/*.tsx'],
    pattern: /\$\{[^}]*(?:req\.body|req\.query|req\.params|request\.GET|request\.POST)[^}]*\}/g,
    confidence: 'high',
    message: 'Potential XSS via unescaped user input in template',
    remediation: 'Use proper template escaping or sanitization libraries',
    cwe: 'CWE-79',
    fixable: false,
  },
  {
    id: 'VG-WEB-005',
    title: 'innerHTML with User Input',
    category: 'web',
    severity: 'critical',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.jsx', '**/*.tsx'],
    pattern: /\.innerHTML\s*=.*(?:\$\{|props\.|state\.)/g,
    confidence: 'high',
    message: 'Potential XSS via innerHTML with dynamic content',
    remediation: 'Use textContent, or sanitize with DOMPurify',
    cwe: 'CWE-79',
    fixable: false,
  },
  {
    id: 'VG-WEB-006',
    title: 'Missing CSRF Protection',
    category: 'web',
    severity: 'warning',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts'],
    pattern: /app\.(post|put|delete)\([^)]*(?!.*csrf)(?!.*xsrf)/gi,
    confidence: 'low',
    message: 'POST/PUT/DELETE endpoint may lack CSRF protection',
    remediation: 'Implement CSRF tokens or SameSite cookies',
    cwe: 'CWE-352',
    fixable: false,
  },
  {
    id: 'VG-WEB-007',
    title: 'Missing Security Headers',
    category: 'web',
    severity: 'warning',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts'],
    pattern: /express\(\)(?!.*helmet)/gs,
    confidence: 'low',
    message: 'Express app missing security headers middleware',
    remediation: 'Use helmet() middleware for security headers',
    cwe: 'CWE-1021',
    fixable: false,
  },
  {
    id: 'VG-WEB-008',
    title: 'Reflected XSS via res.send',
    category: 'web',
    severity: 'critical',
    languages: ['node', 'typescript'],
    filePatterns: ['**/*.js', '**/*.ts', '**/*.mjs', '**/*.cjs'],
    // res.send / res.write / res.end with untrusted request data
    pattern: /res\.(?:send|write|end)\s*\([^)]*(?:req\.(?:body|query|params|headers)|request\.(?:GET|POST))/g,
    confidence: 'high',
    message: 'Reflecting raw request data back in the response causes XSS',
    remediation: 'Escape with a templating engine, or send JSON via res.json() with a strict Content-Type',
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fixable: false,
  },
];
